version: "3"
services:
  smartcities:
    image: smartcities
    container_name: smartcities
    restart: always
    ports:
      - 3000:3000
      - 3500:3500
      - 3200:3200
      - 27017:27017

      ## docker build -t smartcities .